.phony: all
all: results/convergence.jsonl results/sherlog.jsonl results/problog.jsonl

results/convergence.jsonl:
	python3 -m smokers sherlog --train 50 --test 10 --size 3 --epochs 10 --log results/convergence.jsonl --convergence
	python3 -m smokers sherlog --train 50 --test 10 --size 3 --epochs 10 --log results/convergence.jsonl --convergence
	python3 -m smokers sherlog --train 50 --test 10 --size 3 --epochs 10 --log results/convergence.jsonl --convergence
	
	python3 -m smokers sherlog --train 50 --test 10 --size 4 --epochs 10 --log results/convergence.jsonl --convergence
	python3 -m smokers sherlog --train 50 --test 10 --size 4 --epochs 10 --log results/convergence.jsonl --convergence
	python3 -m smokers sherlog --train 50 --test 10 --size 4 --epochs 10 --log results/convergence.jsonl --convergence
	
	python3 -m smokers sherlog --train 50 --test 10 --size 5 --epochs 10 --log results/convergence.jsonl --convergence
	python3 -m smokers sherlog --train 50 --test 10 --size 5 --epochs 10 --log results/convergence.jsonl --convergence
	python3 -m smokers sherlog --train 50 --test 10 --size 5 --epochs 10 --log results/convergence.jsonl --convergence
	
	python3 -m smokers sherlog --train 50 --test 10 --size 6 --epochs 10 --log results/convergence.jsonl --convergence
	python3 -m smokers sherlog --train 50 --test 10 --size 6 --epochs 10 --log results/convergence.jsonl --convergence
	python3 -m smokers sherlog --train 50 --test 10 --size 6 --epochs 10 --log results/convergence.jsonl --convergence
	
	python3 -m smokers sherlog --train 50 --test 10 --size 7 --epochs 10 --log results/convergence.jsonl --convergence
	python3 -m smokers sherlog --train 50 --test 10 --size 7 --epochs 10 --log results/convergence.jsonl --convergence
	python3 -m smokers sherlog --train 50 --test 10 --size 7 --epochs 10 --log results/convergence.jsonl --convergence
	
	python3 -m smokers sherlog --train 50 --test 10 --size 8 --epochs 10 --log results/convergence.jsonl --convergence
	python3 -m smokers sherlog --train 50 --test 10 --size 8 --epochs 10 --log results/convergence.jsonl --convergence
	python3 -m smokers sherlog --train 50 --test 10 --size 8 --epochs 10 --log results/convergence.jsonl --convergence
	
results/sherlog.jsonl:
	python3 -m smokers sherlog --train 10 --test 10 --size 3 --epochs 5 --log results/sherlog.jsonl
	python3 -m smokers sherlog --train 10 --test 10 --size 3 --epochs 5 --log results/sherlog.jsonl
	python3 -m smokers sherlog --train 10 --test 10 --size 3 --epochs 5 --log results/sherlog.jsonl
	
	python3 -m smokers sherlog --train 100 --test 10 --size 3 --epochs 5 --log results/sherlog.jsonl
	python3 -m smokers sherlog --train 100 --test 10 --size 3 --epochs 5 --log results/sherlog.jsonl
	python3 -m smokers sherlog --train 100 --test 10 --size 3 --epochs 5 --log results/sherlog.jsonl
	
	python3 -m smokers sherlog --train 50 --test 10 --size 5 --epochs 5 --log results/sherlog.jsonl
	python3 -m smokers sherlog --train 50 --test 10 --size 5 --epochs 5 --log results/sherlog.jsonl
	python3 -m smokers sherlog --train 50 --test 10 --size 5 --epochs 5 --log results/sherlog.jsonl
	
	python3 -m smokers sherlog --train 50 --test 10 --size 7 --epochs 5 --log results/sherlog.jsonl
	python3 -m smokers sherlog --train 50 --test 10 --size 7 --epochs 5 --log results/sherlog.jsonl
	python3 -m smokers sherlog --train 50 --test 10 --size 7 --epochs 5 --log results/sherlog.jsonl
	
	python3 -m smokers sherlog --train 50 --test 10 --size 9 --epochs 5 --log results/sherlog.jsonl
	python3 -m smokers sherlog --train 50 --test 10 --size 9 --epochs 5 --log results/sherlog.jsonl
	python3 -m smokers sherlog --train 50 --test 10 --size 9 --epochs 5 --log results/sherlog.jsonl
	
	python3 -m smokers sherlog --train 50 --test 10 --size 11 --epochs 5 --log results/sherlog.jsonl
	python3 -m smokers sherlog --train 50 --test 10 --size 11 --epochs 5 --log results/sherlog.jsonl
	python3 -m smokers sherlog --train 50 --test 10 --size 11 --epochs 5 --log results/sherlog.jsonl
	
results/problog.jsonl:
	python3 -m smokers problog --train 10 --test 10 --size 3 --log results/problog.jsonl
	python3 -m smokers problog --train 10 --test 10 --size 3 --log results/problog.jsonl
	python3 -m smokers problog --train 10 --test 10 --size 3 --log results/problog.jsonl
	
	python3 -m smokers problog --train 100 --test 10 --size 3 --log results/problog.jsonl
	python3 -m smokers problog --train 100 --test 10 --size 3 --log results/problog.jsonl
	python3 -m smokers problog --train 100 --test 10 --size 3 --log results/problog.jsonl
	
	python3 -m smokers problog --train 50 --test 10 --size 5 --log results/problog.jsonl
	python3 -m smokers problog --train 50 --test 10 --size 5 --log results/problog.jsonl
	python3 -m smokers problog --train 50 --test 10 --size 5 --log results/problog.jsonl
	
	python3 -m smokers problog --train 50 --test 10 --size 7 --log results/problog.jsonl
	python3 -m smokers problog --train 50 --test 10 --size 7 --log results/problog.jsonl
	python3 -m smokers problog --train 50 --test 10 --size 7 --log results/problog.jsonl
	
	python3 -m smokers problog --train 50 --test 10 --size 9 --log results/problog.jsonl
	python3 -m smokers problog --train 50 --test 10 --size 9 --log results/problog.jsonl
	python3 -m smokers problog --train 50 --test 10 --size 9 --log results/problog.jsonl
	
	python3 -m smokers problog --train 50 --test 10 --size 11 --log results/problog.jsonl
	python3 -m smokers problog --train 50 --test 10 --size 11 --log results/problog.jsonl
	python3 -m smokers problog --train 50 --test 10 --size 11 --log results/problog.jsonl
	